### ISSUE TITLE
Errors in post_IDallocation.gff

### ISSUE THREAD

**Issue by obsidian83** [VEuPathDB/stable_identifier_authority#6]
Looking at the post_IDallocation file there were multiple errors with the IDs. Some IDs were missing, others were replicated

e.g. 
KB704125	VectorBase	mRNA	6633701	6634925	.	-	.	ID=;Parent=AARA007632;

KB704125	VectorBase	gene	4085	4785	.	-	.	ID=AARA007236;
KB704125	VectorBase	mRNA	4085	4785	.	-	.	ID=AARA002614.R24383;
KB704125	VectorBase	gene	5170253	5189236	.	+	.	ID=AARA007510;
KB704125	VectorBase	mRNA	5170253	5189236	.	+	.	ID=AARA002614.R24383;

Thanks

**Comment by mbc32** [comment]
Hi David,
I have compared the original file and the file I downloaded from slack, they are different, exactly how that happened I do not know. But I have tested the original file and all 1422 mRNA have an unique ID. 
Looking at the same line in the original file I get:
KB704125        VectorBase      gene    4085    4785    .       -       .       ID=AARA007236;
KB704125        VectorBase      mRNA    4085    4785    .       -       .       ID=AARA007236.R51035;Parent=AARA007236

Looking in the file I downloaded from slack i get:
KB704125        VectorBase      gene    4085    4785    .       -       .       ID=AARA007236
KB704125        VectorBase      mRNA    4085    4785    .       -       .       ID=AARA002614.R24383;Parent=AARA007236;
